### ISSUE TITLE
Tie sidebar open/closed state to the hostname

### ISSUE THREAD

**Issue by yewsiang** [frizensami/webpage-discussion-extension#17]
After the user closed the sidebar, it gets reopened if the user clicks around because there is a re-render - this will be irritating. We should tie the state to the hostname and not reopen the sidebar if it has been closed.

**Comment by frizensami** [comment]
I think 
- close for all tabs but indicate how many discussions were found 
- might be useful to have a little animation with the number of discussion found? Like a little popup that extends from the button with the number of discussions, like a "number of notifications"
- 
https://i.pinimg.com/originals/e8/75/96/e8759658d95aa696adb9b1dd026d6653.gif -- same broad concept as this?

**Comment by frizensami** [comment]
Okay yeah I ran into the same issue dogfooding today, either we
1. Allow the user to blacklist URLs where the sidebar shouldn't open + open the sidebar by default
2. Allow the user to whitelist URLs where the side should open + close the side bar by default
3. Close the sidebar by default and animate the button with info if we find discussions for that page (and they can choose to open) -- I **personally think this is the best solution, since we don't get situations where the sidebar has 0 discussions and is deadweight**

![image](https://user-images.githubusercontent.com/5507069/155049143-7511d9fd-9a17-4e08-96f2-f284184c1fd5.png)

**Comment by frizensami** [comment]
Part of #52
